練習問題 6-13で準備したデータに対して、NaNを0で埋めてください。

In [1]:
import numpy as np
import pandas as pd

In [1]:
# データの準備
import numpy as np
from numpy import nan as NA
import pandas as pd
df2 = pd.DataFrame(np.random.rand(15,6))
# NA にする
df2.iloc[2,0] = NA
df2.iloc[5:9,2] = NA
df2.iloc[7:10,3] = NA
df2.iloc[10,5] = NA
df2

           0         1         2         3         4         5
0   0.228592  0.294973  0.836087  0.331664  0.302404  0.795542
1   0.220366  0.299412  0.582373  0.931411  0.458462  0.714172
2        NaN  0.918742  0.152223  0.861569  0.118994  0.448030
3   0.386933  0.043786  0.434586  0.088626  0.496656  0.499927
4   0.305624  0.606166  0.834990  0.317676  0.663686  0.779835
5   0.554539  0.476370       NaN  0.288101  0.036526  0.522838
6   0.569394  0.539077       NaN  0.534862  0.555078  0.171719
7   0.031478  0.042527       NaN       NaN  0.095481  0.463212
8   0.732889  0.760798       NaN       NaN  0.181949  0.010720
9   0.779114  0.673481  0.848673       NaN  0.481025  0.686088
10  0.151393  0.945799  0.066660  0.870441  0.536306       NaN
11  0.563965  0.491071  0.559171  0.210976  0.414867  0.868542
12  0.800291  0.463964  0.734168  0.628446  0.223991  0.594253
13  0.808510  0.499244  0.982057  0.944794  0.092935  0.837952
14  0.636112  0.132743  0.417404  0.168406  0.463419  0.750974

In [4]:
df2.fillna(0)

           0         1         2         3         4         5
0   0.228592  0.294973  0.836087  0.331664  0.302404  0.795542
1   0.220366  0.299412  0.582373  0.931411  0.458462  0.714172
2   0.000000  0.918742  0.152223  0.861569  0.118994  0.448030
3   0.386933  0.043786  0.434586  0.088626  0.496656  0.499927
4   0.305624  0.606166  0.834990  0.317676  0.663686  0.779835
5   0.554539  0.476370  0.000000  0.288101  0.036526  0.522838
6   0.569394  0.539077  0.000000  0.534862  0.555078  0.171719
7   0.031478  0.042527  0.000000  0.000000  0.095481  0.463212
8   0.732889  0.760798  0.000000  0.000000  0.181949  0.010720
9   0.779114  0.673481  0.848673  0.000000  0.481025  0.686088
10  0.151393  0.945799  0.066660  0.870441  0.536306  0.000000
11  0.563965  0.491071  0.559171  0.210976  0.414867  0.868542
12  0.800291  0.463964  0.734168  0.628446  0.223991  0.594253
13  0.808510  0.499244  0.982057  0.944794  0.092935  0.837952
14  0.636112  0.132743  0.417404  0.168406  0.463419  0.750974