練習問題 6-13で準備したデータに対して、NaNをそれぞれの列の平均値で埋めてください。

In [1]:
import numpy as np
import pandas as pd

In [2]:
# データの準備
import numpy as np
from numpy import nan as NA
import pandas as pd
df2 = pd.DataFrame(np.random.rand(15,6))
# NA にする
df2.iloc[2,0] = NA
df2.iloc[5:9,2] = NA
df2.iloc[7:10,3] = NA
df2.iloc[10,5] = NA
df2

           0         1         2         3         4         5
0   0.739209  0.564723  0.787057  0.068815  0.065718  0.372580
1   0.918788  0.971821  0.463495  0.957212  0.439694  0.382544
2        NaN  0.663312  0.182607  0.495881  0.230451  0.474581
3   0.443155  0.732710  0.481457  0.164095  0.601044  0.616073
4   0.897906  0.809252  0.204861  0.300860  0.553901  0.787678
5   0.686542  0.976737       NaN  0.468366  0.672132  0.909868
6   0.034955  0.640337       NaN  0.834688  0.013519  0.036553
7   0.580635  0.492013       NaN       NaN  0.459849  0.405997
8   0.269230  0.404865       NaN       NaN  0.365163  0.152691
9   0.334989  0.239621  0.805794       NaN  0.609027  0.035951
10  0.122311  0.952599  0.416746  0.940510  0.815186       NaN
11  0.046041  0.403041  0.355259  0.372961  0.882837  0.541226
12  0.332509  0.650397  0.669765  0.615246  0.765335  0.848553
13  0.516534  0.520637  0.203083  0.498074  0.239757  0.770716
14  0.678191  0.310204  0.006181  0.711673  0.890837  0.199356

In [3]:
df2.fillna(df2.mean())

           0         1         2         3         4         5
0   0.739209  0.564723  0.787057  0.068815  0.065718  0.372580
1   0.918788  0.971821  0.463495  0.957212  0.439694  0.382544
2   0.471500  0.663312  0.182607  0.495881  0.230451  0.474581
3   0.443155  0.732710  0.481457  0.164095  0.601044  0.616073
4   0.897906  0.809252  0.204861  0.300860  0.553901  0.787678
5   0.686542  0.976737  0.416028  0.468366  0.672132  0.909868
6   0.034955  0.640337  0.416028  0.834688  0.013519  0.036553
7   0.580635  0.492013  0.416028  0.535698  0.459849  0.405997
8   0.269230  0.404865  0.416028  0.535698  0.365163  0.152691
9   0.334989  0.239621  0.805794  0.535698  0.609027  0.035951
10  0.122311  0.952599  0.416746  0.940510  0.815186  0.466740
11  0.046041  0.403041  0.355259  0.372961  0.882837  0.541226
12  0.332509  0.650397  0.669765  0.615246  0.765335  0.848553
13  0.516534  0.520637  0.203083  0.498074  0.239757  0.770716
14  0.678191  0.310204  0.006181  0.711673  0.890837  0.199356