以下のデータに対して、1 列でもNaNがある場合は削除し、その結果を表示してください。

In [1]:
import numpy as np
import pandas as pd

In [2]:
# データの準備
import numpy as np
from numpy import nan as NA
import pandas as pd
df2 = pd.DataFrame(np.random.rand(15,6))
# NA にする
df2.iloc[2,0] = NA
df2.iloc[5:9,2] = NA
df2.iloc[7:10,3] = NA
df2.iloc[10,5] = NA
df2

           0         1         2         3         4         5
0   0.396374  0.083528  0.307113  0.289386  0.471519  0.756945
1   0.272246  0.444908  0.407070  0.758732  0.017778  0.087886
2        NaN  0.278455  0.569626  0.527072  0.697693  0.485781
3   0.709764  0.225689  0.612702  0.774854  0.708916  0.999329
4   0.505445  0.380212  0.410747  0.858345  0.782550  0.508575
5   0.833711  0.264342       NaN  0.928206  0.835516  0.669562
6   0.617562  0.747893       NaN  0.805233  0.070152  0.238531
7   0.433248  0.766423       NaN       NaN  0.330981  0.900376
8   0.118592  0.049321       NaN       NaN  0.677635  0.766845
9   0.158700  0.158049  0.179828       NaN  0.303540  0.133295
10  0.722835  0.055697  0.930032  0.058776  0.413410       NaN
11  0.767471  0.969411  0.488635  0.632367  0.990792  0.606282
12  0.764501  0.745057  0.890218  0.213986  0.145883  0.507725
13  0.928846  0.963682  0.473458  0.970062  0.842440  0.551228
14  0.695125  0.062575  0.824435  0.716315  0.299087  0.676396

In [6]:
df2.dropna()

           0         1         2         3         4         5
0   0.396374  0.083528  0.307113  0.289386  0.471519  0.756945
1   0.272246  0.444908  0.407070  0.758732  0.017778  0.087886
3   0.709764  0.225689  0.612702  0.774854  0.708916  0.999329
4   0.505445  0.380212  0.410747  0.858345  0.782550  0.508575
11  0.767471  0.969411  0.488635  0.632367  0.990792  0.606282
12  0.764501  0.745057  0.890218  0.213986  0.145883  0.507725
13  0.928846  0.963682  0.473458  0.970062  0.842440  0.551228
14  0.695125  0.062575  0.824435  0.716315  0.299087  0.676396